/**
 * Static image imports.
 *
 * Next writes these declarations into `next-env.d.ts`, but that file is
 * generated by `next dev` / `next build` and is gitignored by Next's own
 * convention. So on a fresh clone `pnpm run typecheck` runs before it exists
 * and every image import fails with TS2307. That is exactly what happened on
 * the dev machine: the code was fine, the type declarations simply had not
 * been generated yet.
 *
 * Referencing the types explicitly, in a file that is committed, makes
 * typecheck deterministic from a clean checkout and in CI, with no dependency
 * on having run a build first.
 */
/// <reference types="next/image-types/global" />
